In [2]:
#!pip install numpy

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("supershops.csv")

In [4]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [44]:
# Eucleadian distance
from sklearn.metrics.pairwise import euclidean_distances

x = np.array([[1,2,5]])
y = np.array([[5,8,6]])

eu = euclidean_distances(x,y)
print(eu)

[[7.28010989]]


In [45]:
x = np.array([[4,1]])
y = np.array([[3,0]])
eu = euclidean_distances(x,y)
eu

array([[1.41421356]])

In [47]:
eu = np.sqrt((x[0,0]-y[0,0])**2 + (x[0,1]-y[0,1])**2)
eu

np.float64(1.4142135623730951)

In [48]:
# Manhaattan Distance
from sklearn.metrics.pairwise import manhattan_distances

x = np.array([[1,2]])
y = np.array([[3,4]])

mnhtn = manhattan_distances(x,y)
mnhtn

array([[4.]])

In [49]:
mnhtn = np.abs(x[0,0]-y[0,0]) + np.abs(x[0,1]-y[0,1])
mnhtn

np.int64(4)

In [50]:
# Minkowski Distance
x = np.array([[2,3]])
y = np.array([[5,7]])

from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('minkowski',p=1) # p = 1 for manhattan distance
dist.pairwise(x,y)

array([[7.]])

In [51]:
# Minkowski Distance with p = 3
mnkdis = ((abs(x[0,0] - y[0,0])**3 + abs(x[0,1] - y[0,1])**3))**(1/3)
mnkdis

np.float64(4.497941445275415)

In [52]:
# minmax scaler
from sklearn.preprocessing import MinMaxScaler
mmx = MinMaxScaler(feature_range=(0, 1))
mmx

MinMaxScaler()

In [55]:
df1 = df.copy()

In [56]:
df1["Marketing Spend"] = mmx.fit_transform(df1[["Marketing Spend"]])

In [57]:
df1.head()

Marketing Spend  Administration  Transport     Area     Profit
0         0.692617       136897.80  471784.10    Dhaka  192261.83
1         0.983359       151377.59  443898.53      Ctg  191792.06
2         0.927985       101145.55  407934.54  Rangpur  191050.39
3         0.873136       118671.85  383199.62    Dhaka  182901.99
4         0.859438        91391.77  366168.42  Rangpur  166187.94

In [60]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Marketing Spend  50 non-null     float64
 1   Administration   50 non-null     float64
 2   Transport        49 non-null     float64
 3   Area             50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [61]:
x = df1.iloc[:, : -1]
y = df1.iloc[:, -1]

In [62]:
x.head()

Marketing Spend  Administration  Transport     Area
0         0.692617       136897.80  471784.10    Dhaka
1         0.983359       151377.59  443898.53      Ctg
2         0.927985       101145.55  407934.54  Rangpur
3         0.873136       118671.85  383199.62    Dhaka
4         0.859438        91391.77  366168.42  Rangpur

In [63]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [68]:
x.columns

Index(['Marketing Spend', 'Administration', 'Transport', 'Area'], dtype='object')

In [69]:
for col in x.columns:
    if x[col].dtypes == "object":
        continue
    x[col] = mmx.fit_transform(x[[col]])

In [70]:
x.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.651744   1.000000    Dhaka
1         0.983359        0.761972   0.940893      Ctg
2         0.927985        0.379579   0.864664  Rangpur
3         0.873136        0.512998   0.812235    Dhaka
4         0.859438        0.305328   0.776136  Rangpur

In [87]:
df2 = df.copy()
df2.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [88]:
# Standarization
from sklearn.preprocessing import StandardScaler
stnscaler = StandardScaler()
stnscaler

StandardScaler()

In [89]:
x = df2.iloc[:, : -1]
y = df2.iloc[:, -1]

In [90]:
x.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [91]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [92]:
for col in x.columns:
    if x[col].dtypes == "object":
        continue
    x[col] = stnscaler.fit_transform(x[[col]])

In [94]:
x.head()

Marketing Spend  Administration  Transport     Area
0         0.897913        0.560753   2.165287    Dhaka
1         1.955860        1.082807   1.929843      Ctg
2         1.754364       -0.728257   1.626191  Rangpur
3         1.554784       -0.096365   1.417348    Dhaka
4         1.504937       -1.079919   1.273550  Rangpur

In [110]:
x = df2['Marketing Spend']
#standarization
xstn = (x - x.mean())/x.std()
x = xstn
x.head()

0    0.888889
1    1.936203
2    1.736731
3    1.539157
4    1.489812
Name: Marketing Spend, dtype: float64

In [111]:
# Log Transformation
x = df2['Marketing Spend']
x_log = np.log1p(x)  # Safer alternative for 0 or negative value because it apply rule n+1
x = x_log
x.head()

C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)


0    11.648531
1    11.999031
2    11.941071
3    11.880147
4    11.864334
Name: Marketing Spend, dtype: float64

In [117]:
x = df2['Marketing Spend']
x_log_scaled = stnscaler.fit_transform(np.log1p(x).values.reshape(-1, 1)) #make 2d
x_log_scaled

C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)


array([[ 0.62982839],
       [ 0.92014866],
       [ 0.8721403 ],
       [ 0.82167706],
       [ 0.80857866],
       [ 0.74669266],
       [ 0.76371717],
       [ 0.7367167 ],
       [ 0.67225563],
       [ 0.69122447],
       [ 0.5331973 ],
       [ 0.52304804],
       [ 0.4650473 ],
       [ 0.44836647],
       [ 0.6681274 ],
       [ 0.93404811],
       [ 0.31183698],
       [ 0.47201939],
       [ 0.4461735 ],
       [ 0.39660523],
       [ 0.29294416],
       [ 0.3158234 ],
       [ 0.2680315 ],
       [ 0.19233863],
       [ 0.30148303],
       [ 0.15639504],
       [ 0.28283498],
       [ 0.24663447],
       [ 0.17397134],
       [ 0.16835886],
       [ 0.1214649 ],
       [ 0.10991969],
       [ 0.14015017],
       [ 0.02971159],
       [-0.11807027],
       [-0.12545472],
       [-0.51750803],
       [-0.16121142],
       [-0.80616874],
       [-0.27187557],
       [-0.51489488],
       [-0.54008868],
       [-0.67708792],
       [-1.0264528 ],
       [-0.73001004],
       [-3

In [118]:
# RobustScaler
from sklearn.preprocessing import RobustScaler
rbstscaler = RobustScaler()
rbstscaler

RobustScaler()

In [119]:
df3 = df.copy()

In [120]:
x = df3.iloc[:, : -1]
y = df3.iloc[:, -1]

In [121]:
for col in x.columns:
    if x[col].dtypes == "object":
        continue
    x[col] = rbstscaler.fit_transform(x[[col]])

In [122]:
x.head()

Marketing Spend  Administration  Transport     Area
0         0.672530        0.345355   1.552016    Dhaka
1         1.452113        0.697565   1.383714      Ctg
2         1.303634       -0.524290   1.166654  Rangpur
3         1.156567       -0.097977   1.017368    Dhaka
4         1.119836       -0.761543   0.914576  Rangpur

In [123]:
x = df3['Marketing Spend']

#Compute Q1 (25th percentile) and Q3 (75th percentile)

Q1 = np.percentile(x, 25)  # First quartile
Q3 = np.percentile(x, 75)  # Third quartile

# Compute Median
median_x = np.median(x)

# Compute Interquartile Range (IQR)
IQR = Q3 - Q1

x_robust_scaled = (x - median_x) / IQR

x_robust_scaled

0     0.672530
1     1.452113
2     1.303634
3     1.156567
4     1.119836
5     0.953936
6     0.998345
7     0.928334
8     0.770134
9     0.815416
10    0.468034
11    0.447908
12    0.337504
13    0.307158
14    0.760416
15    1.496732
16    0.080466
17    0.350370
18    0.303213
19    0.216789
20    0.051937
21    0.086569
22    0.015300
23   -0.089490
24    0.064750
25   -0.135996
26    0.036937
27   -0.015300
28   -0.113507
29   -0.120740
30   -0.179297
31   -0.193212
32   -0.156361
33   -0.284711
34   -0.431759
35   -0.438440
36   -0.719797
37   -0.469966
38   -0.856568
39   -0.559341
40   -0.718328
41   -0.732297
42   -0.801249
43   -0.933171
44   -0.824976
45   -1.168397
46   -1.163285
47   -1.184617
48   -1.175827
49   -1.184617
Name: Marketing Spend, dtype: float64

In [5]:
df4 = df.copy()

In [7]:
df4.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [8]:
# Maxabsscaler compute
from sklearn.preprocessing import MaxAbsScaler
maxabsscaler = MaxAbsScaler()
maxabsscaler

MaxAbsScaler()

In [10]:
x = df4.iloc[:, : -1]
y = df4.iloc[:, -1]

In [11]:
x.head()

Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [12]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [13]:
x.columns

Index(['Marketing Spend', 'Administration', 'Transport', 'Area'], dtype='object')

In [14]:
for col in x.columns:
    if x[col].dtypes == "object":
        continue
    x[col] = maxabsscaler.fit_transform(x[[col]])

In [15]:
x.head()

Marketing Spend  Administration  Transport     Area
0         0.692617        0.749527   1.000000    Dhaka
1         0.983359        0.828805   0.940893      Ctg
2         0.927985        0.553781   0.864664  Rangpur
3         0.873136        0.649738   0.812235    Dhaka
4         0.859438        0.500378   0.776136  Rangpur

In [22]:
x = df4['Marketing Spend']
if max(x) == 0:
    print("Division by zero error.")
else:
    xmaxabsscaler = x / max(x)
df4[['Marketing Spend']] = xmaxabsscaler.values.reshape(-1, 1)

In [23]:
df4['Marketing Spend'].head()

0    0.692617
1    0.983359
2    0.927985
3    0.873136
4    0.859438
Name: Marketing Spend, dtype: float64